FROM ubuntu:16.04

MAINTAINER Potier Delphine (potier@ciml.univ-mrs.fr)

# ##################################
# INSTALLING R FROM SOURCES
# ##################################

ARG R_VERSION
ARG BUILD_DATE
ENV R_VERSION=${R_VERSION:-3.5.3} 
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

## dependencies
RUN apt-get update && apt-get install -y  apt-utils
RUN apt-get update \ 
  && apt-get install -y  python3.5 python3-pip build-essential pkg-config libffi-dev libmagickwand-dev python-cffi python3-dev 


RUN apt-get update --fix-missing \ 
  && apt-get install -y --no-install-recommends \
    bash-completion \
    ca-certificates \
    file \
    fonts-texgyre \
    g++ \
    gfortran \
    gsfonts \
    libbz2-1.0 \
    libcurl3 \
    libicu55 \
    libturbojpeg \
    libopenblas-dev \
    libpangocairo-1.0-0 \ 
    libpcre3 \
    libpng12-0 \
    libtiff5 \ 
    liblzma5 \
    locales \
    make \
    unzip \
    zip \
    zlib1g \
  && echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen \
  && locale-gen en_US.utf8 \
  && /usr/sbin/update-locale LANG=en_US.UTF-8 \
  && BUILDDEPS="curl \
    default-jdk \
    libbz2-dev \
    libcairo2-dev \ 
    libcurl4-openssl-dev \
    libpango1.0-dev \
    libjpeg-dev \
    libicu-dev \
    libpcre3-dev \
    libpng-dev \
    libreadline-dev \
    libtiff5-dev \
    liblzma-dev \ 
    libx11-dev \
    libxt-dev \
    perl \
    texinfo \
    texlive-extra-utils \
    texlive-fonts-recommended \
    texlive-fonts-extra \
    texlive-latex-recommended \
    x11proto-core-dev \
    xauth \
    xfonts-base \
    xvfb \
    zlib1g-dev" \
  && apt-get install -y --no-install-recommends $BUILDDEPS \ 
  && cd tmp/ \
## Download source code 
  && curl -O https://cran.r-project.org/src/base/R-3/R-${R_VERSION}.tar.gz \
## Extract source code
  && tar -xf R-${R_VERSION}.tar.gz \
  && cd R-${R_VERSION} \
## Set compiler flags
  && R_PAPERSIZE=letter \
    R_BATCHSAVE="--no-save --no-restore" \
    R_BROWSER=xdg-open \
    PAGER=/usr/bin/pager \
    PERL=/usr/bin/perl \
    R_UNZIPCMD=/usr/bin/unzip \
    R_ZIPCMD=/usr/bin/zip \
    R_PRINTCMD=/usr/bin/lpr \
    LIBnn=lib \
    AWK=/usr/bin/awk \
    CFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g" \
    CXXFLAGS="-g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g" \
## Configure options
  ./configure --enable-R-shlib \
               --enable-memory-profiling \
               --with-readline \
               --with-blas="-lopenblas" \
               --disable-nls \
               --without-recommended-packages \
## Build and install
  && make \
  && make install \
## Add a default CRAN mirror
  && echo "options(repos = c(CRAN = 'https://cran.rstudio.com/'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site \
## Add a library directory (for user-installed packages)
  && mkdir -p /usr/local/lib/R/site-library \
  && chown root:staff /usr/local/lib/R/site-library \
  && chmod g+wx /usr/local/lib/R/site-library \
## Fix library path
  && echo "R_LIBS_USER='/usr/local/lib/R/site-library'" >> /usr/local/lib/R/etc/Renviron \
  && echo "R_LIBS=\${R_LIBS-'/usr/local/lib/R/site-library:/usr/local/lib/R/library:/usr/lib/R/library'}" >> /usr/local/lib/R/etc/Renviron \
## install packages from date-locked MRAN snapshot of CRAN
  && [ -z "$BUILD_DATE" ] && BUILD_DATE=$(date -I --date='TZ="America/Los_Angeles"') || true \
  && MRAN=https://mran.microsoft.com/snapshot/${BUILD_DATE} \
  && echo MRAN=$MRAN >> /etc/environment \
  && export MRAN=$MRAN \
  && echo "options(repos = c(CRAN='$MRAN'), download.file.method = 'libcurl')" >> /usr/local/lib/R/etc/Rprofile.site \
## Use littler installation scripts
  && Rscript -e "install.packages(c('littler', 'docopt'), repo = '$MRAN')" \
  && ln -s /usr/local/lib/R/site-library/littler/examples/install2.r /usr/local/bin/install2.r \
  && ln -s /usr/local/lib/R/site-library/littler/examples/installGithub.r /usr/local/bin/installGithub.r \
  && ln -s /usr/local/lib/R/site-library/littler/bin/r /usr/local/bin/r \
## Clean up from R source install
  && cd / \
  && rm -rf /tmp/* \
  && apt-get remove --purge -y $BUILDDEPS \
  && apt-get autoremove -y \
  && apt-get autoclean -y \
  && rm -rf /var/lib/apt/lists/*


# ##################################
# INSTALLING RSTUDIO SERVER
# ##################################

ARG RSTUDIO_VERSION
ENV RSTUDIO_VERSION ${RSTUDIO_VERSION:-1.1.463}
ARG PANDOC_TEMPLATES_VERSION 
ENV PANDOC_TEMPLATES_VERSION ${PANDOC_TEMPLATES_VERSION:-2.7.2}


## Add RStudio binaries to PATH
ENV PATH=/usr/lib/rstudio-server/bin:$PATH

## Download and install RStudio server & dependencies
## Attempts to get detect latest version, otherwise falls back to version given in $VER
## Symlink pandoc, pandoc-citeproc so they are available system-wide
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    file \
    git \
    libapparmor1 \
    libcurl4-openssl-dev \
    libedit2 \
    libssl-dev \
    lsb-release \
    psmisc \
    python-setuptools \
    sudo \
    wget \ 
&& RSTUDIO_LATEST=$(wget --no-check-certificate -qO- https://s3.amazonaws.com/rstudio-server/rstudio-server-1.1.463-amd64.deb) \
  && [ -z "$RSTUDIO_VERSION" ] && RSTUDIO_VERSION=$RSTUDIO_LATEST || true \
  && wget -q http://download2.rstudio.org/rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
  && dpkg -i rstudio-server-${RSTUDIO_VERSION}-amd64.deb \
  && rm rstudio-server-*-amd64.deb \
  ## Symlink pandoc & standard pandoc templates for use system-wide
  && ln -s /usr/lib/rstudio-server/bin/pandoc/pandoc /usr/local/bin \
  && ln -s /usr/lib/rstudio-server/bin/pandoc/pandoc-citeproc /usr/local/bin \
  && git clone https://github.com/jgm/pandoc-templates \
  && mkdir -p /opt/pandoc/templates \
  && cp -r pandoc-templates*/* /opt/pandoc/templates && rm -rf pandoc-templates* \
  && mkdir /root/.pandoc && ln -s /opt/pandoc/templates /root/.pandoc/templates \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && rm -rf /var/lib/apt/lists/ \
  && mkdir -p /usr/local/lib/R/etc \
  ## RStudio wants an /etc/R, will populate from $R_HOME/etc
  && mkdir -p /etc/R \
  ## Write config files in $R_HOME/etc
  && echo '\n\
    \n# Configure httr to perform out-of-band authentication if HTTR_LOCALHOST \
    \n# is not set since a redirect to localhost may not work depending upon \
    \n# where this Docker container is running. \
    \nif(is.na(Sys.getenv("HTTR_LOCALHOST", unset=NA))) { \
    \n  options(httr_oob_default = TRUE) \
    \n}' >> /usr/local/lib/R/etc/Rprofile.site \
  && echo "PATH=${PATH}" >> /usr/local/lib/R/etc/Renviron \
  ## Prevent rstudio from deciding to use /usr/bin/R if a user apt-get installs a package
  &&  echo 'rsession-which-r=/usr/local/bin/R' >> /etc/rstudio/rserver.conf \
  ## use more robust file locking to avoid errors when using shared volumes:
  && echo 'lock-type=advisory' >> /etc/rstudio/file-locks \
  ## configure git not to request password each time
  && git config --system credential.helper 'cache --timeout=3600' \
  && git config --system push.default simple \
  ## Set up S6 init system
  && wget -P /tmp/ https://github.com/just-containers/s6-overlay/releases/download/v1.11.0.1/s6-overlay-amd64.tar.gz \
  && tar xzf /tmp/s6-overlay-amd64.tar.gz -C / \
  && mkdir -p /etc/services.d/rstudio \
  && echo '#!/usr/bin/with-contenv bash \
           \n exec /usr/lib/rstudio-server/bin/rserver --server-daemonize 0' \
           > /etc/services.d/rstudio/run \
   && echo '#!/bin/bash \
           \n rstudio-server stop' \
           > /etc/services.d/rstudio/finish

COPY userconf.sh /etc/cont-init.d/conf
EXPOSE 8787




# ####################################
# INSTALL JAVA
# ####################################

# Install tools for add-apt-repository
RUN  apt-get update  && apt-get install -y software-properties-common software-properties-common

# Configure the silent mode for the Oracle Java installation (bypass accept licence question)
RUN echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
RUN echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections

# Install Java 11

RUN add-apt-repository ppa:linuxuprising/java

RUN echo oracle-java11-installer shared/accepted-oracle-license-v1-2 select true | sudo /usr/bin/debconf-set-selections
RUN apt-get update && apt-get install -y oracle-java11-installer
RUN apt-get install -y  oracle-java11-set-default





# ########################################
# INSTALLING Latex for sweave compilation
# ########################################

RUN apt-get update --fix-missing \ 
  && apt-get -y install texlive-full



# ####################################
# INSTALLING R PACKAGES FOR PROJECT
# ####################################

RUN apt-get update && apt-get install -y libxml2-dev libhdf5-serial-dev libudunits2-dev imagemagick libhdf5-dev zlib1g-dev 
RUN  apt-get update \ 
  && export DEBIAN_FRONTEND=noninteractive \
  && apt-get -y install libx11-dev freeglut3 freeglut3-dev libpng-dev \
  && apt-get -y install xorg openbox



RUN R -e 'install.packages( "knitr")'
RUN R -e 'install.packages( "ade4")'
RUN R -e 'install.packages( "ggplot2")'
RUN R -e 'install.packages( "magrittr")'
RUN R -e 'install.packages( "dplyr")'
RUN R -e 'install.packages( "Rtsne")'
RUN R -e 'install.packages( "ggrepel")'
RUN R -e 'install.packages( "Rcpp")'

RUN R -e 'install.packages( "rprojroot")'
RUN R -e 'install.packages( "rmarkdown")'
RUN R -e 'install.packages( "htmltools")'
RUN R -e 'install.packages( "reshape")'
RUN R -e 'install.packages( "gridExtra")'
RUN R -e 'install.packages( "openxlsx")'
RUN R -e 'install.packages( "corrplot")'
RUN R -e 'install.packages( "reticulate")'
RUN R -e 'install.packages( "feather")'
RUN R -e 'install.packages( "devtools")'
RUN R -e 'install.packages("Seurat")'
RUN R -e 'install.packages( "sctransform")'
RUN R -e 'library(devtools);devtools::install_github("rstudio/DT")'
RUN R -e 'install.packages( "BiocManager")'
RUN R -e 'BiocManager::install()'
RUN R -e 'library(BiocManager)'
RUN R -e 'install.packages("BiocInstaller")'
RUN R -e 'BiocManager::install("BiocInstaller", version = "3.8")'

RUN R -e 'BiocManager::install("monocle", version = "3.8")'
RUN R -e 'install.packages("DDRTree")'
RUN R -e 'install.packages("pheatmap")'
RUN R -e 'install.packages("kable")'
RUN R -e 'install.packages("kableExtra")'
RUN R -e 'install.packages("reshape2")'
RUN R -e 'install.packages("scran")'
RUN R -e 'install.packages("clusterProfiler")'
RUN R -e 'install.packages("org.Mm.eg.db")'
#RUN R -e 'source("http://bioconductor.org/biocLite.R");biocLite("kable")'
#RUN R -e 'source("http://bioconductor.org/biocLite.R");biocLite("kableExtra")'
#RUN R -e 'source("http://bioconductor.org/biocLite.R");biocLite("reshape2")'
#RUN R -e 'source("http://bioconductor.org/biocLite.R");biocLite("scran")'
#RUN R -e 'source("http://bioconductor.org/biocLite.R");biocLite("clusterProfiler")'
#RUN R -e 'source("http://bioconductor.org/biocLite.R");biocLite("org.Mm.eg.db")'
RUN R -e 'source("http://cf.10xgenomics.com/supp/cell-exp/rkit-install-2.0.0.R")'
RUN R -e 'devtools::install_github("chris-mcginnis-ucsf/DoubletFinder")'


RUN apt-get install -y libpcap-dev libpq-dev
RUN apt-get install -y python3-numpy
RUN apt-get install -y python3-tk
RUN pip3 install pandas
RUN pip3 install feather-format
RUN pip3 install nbconvert
RUN pip3 install patsy 
RUN pip3 install sklearn
RUN pip3 install umap-learn

RUN pip3 install git+https://github.com/Teichlab/NaiveDE.git
RUN pip3 install scipy
RUN pip3 install tqdm
RUN rm -f /usr/bin/python 
RUN ln -s /usr/bin/python3 /usr/bin/python

RUN install.packages("devtools")
RUN devtools::install_github(repo="hhoeflin/hdf5r")
RUN devtools::install_github(repo="mojaveazure/loomR, ref=develop")

CMD ["/init"]
